//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Country
    {
        public long ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
