//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CareTracking
    {
        public int ID { get; set; }
        public int Status { get; set; }
        public System.DateTime CareDate { get; set; }
        public Nullable<int> BusinessCenterID { get; set; }
        public Nullable<int> MachineGroupID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string CareDescription { get; set; }
        public Nullable<int> CareType { get; set; }
        public Nullable<int> PlanedCareType { get; set; }
        public Nullable<int> CareTeamType { get; set; }
        public Nullable<int> StateType { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
