//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> LoginFailedCount { get; set; }
        public string LoginIPAddress { get; set; }
        public Nullable<System.DateTime> LastAccessedDate { get; set; }
        public Nullable<int> AccountLocked { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
    }
}
